### ISSUE TITLE
Generator fails with Ruby 2.7.1

### ISSUE THREAD

**Issue by marcamillion** [excid3/jumpstart#104]
I was trying to run it with Ruby `2.7.1`, and this is where it failed:

```
└─ popper.js@1.16.1
✨  Done in 7.04s.
      insert  config/webpack/environment.js
    generate  model Announcement published_at:datetime announcement_type name description:text
       rails  generate model Announcement published_at:datetime announcement_type name description:text 
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
/.rvm/gems/ruby-2.7.1@myapp/gems/activerecord-6.0.2.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for User (call 'User.connection' to establish a connection):Class (NoMethodError)
```

Once I created a new gemset for `2.7.0` and re-ran the generator, everything worked perfectly.

**Comment by excid3** [comment]
It sounds like Devise didn't succeed or something.

Does it work if you run the whole thing with `DISABLE_SPRING=1 rails new ...` ?

**Comment by marcamillion** [comment]
Yes it does work if I run it with `DISABLE_SPRING=1 rails new....`

**Comment by excid3** [comment]
Spring sometimes breaks if you create an app twice with the same name. Just have to disable spring. I've been meaning to add that to the README.

**Comment by marcamillion** [comment]
Ahh ok cool.

Yeah, it had failed for another reason initially and recreated it after, but I did delete the original app and this happened.

**Comment by excid3** [comment]
Yep, that'd do it. Just updated the readme with a mention of that.
