### ISSUE TITLE
Using template.rb - noticed installer requires database to exist?

### ISSUE THREAD

**Issue by davidlowry** [excid3/jumpstart#106]
In the templated installer, the announcement then the noticed installs happen before db:create. Announcement works okay, but Noticed seems to trigger a database call and breaks as per below.  I assume the difference between these two similar installs is that the Announcement command creates a migration, the other instantiates in a different way (**s for emphasis)?

Starting from fresh install, mac osx catalina, yarn 1.22.4 ruby 2.6.3. I've tried multiple steps to fix (dropping in and creating database, rerunning yarn, etc., but always fails here or on another migration step after one of these attempts). Same behaviour using the DISABLE_SPRING=1 flag. I've also tried re-creating as 'fresh' app names rather than repeatedly re-running.

Many thanks in advance... can I do anything to help further reveal cause of issue?

```
def add_announcements
  generate "**model Announcement published_at:datetime announcement_type name description:text**"
  route "resources :announcements, only: [:index]"
end

def add_notifications
  generate "**noticed:model**"
  route "resources :notifications, only: [:index]"
end

```

```
# YARN stuff then...
  Done in 5.06s.
      insert  config/webpack/environment.js
    generate  model Announcement published_at:datetime announcement_type name description:text
       rails  generate model Announcement published_at:datetime announcement_type name description:text
Running via Spring preloader in process 39814
      invoke  active_record
      create    db/migrate/20200820091455_create_announcements.rb
      create    app/models/announcement.rb
      invoke    test_unit
      create      test/models/announcement_test.rb
      create      test/fixtures/announcements.yml
       route  resources :announcements, only: [:index]
    generate  noticed:model
       rails  generate noticed:model
Running via Spring preloader in process 39816
Traceback (most recent call last):
	51: from -e:1:in <main>'
	50: from /Users/david/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in require'
.....
/Users/david/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg.rb:58:in `initialize': FATAL:  database "app_name_development" does not exist (PG::ConnectionBad)
	37: from bin/rails:9:in `<main>'
```

**Comment by excid3** [comment]
I'm pretty sure it's because I updated the noticed gem recently to generate a column on the notifications table based upon the database we're using. Need to go back and update this to match that change.

**Comment by excid3** [comment]
Just pushed up a new version of the `noticed` gem (v1.2.11) that should fix this. 👍

**Comment by davidlowry** [comment]
Confirmed - that fixes the problem. Thanks for these great tools as ever Chris.

**Comment by excid3** [comment]
Awesome, thanks for testing it @davidlowry 🙏 

I also just pushed up two new tests so we can make sure changes continue to work with SQLite, Postgres, and MySQL. 👍 

Won't necessarily help when a dependency changes, but at least it should be more thorough.
