### ISSUE TITLE
AvatarAttachmentDashboard error on clean app

### ISSUE THREAD

**Issue by davidlowry** [excid3/jumpstart#108]
Steps to reproduce:
- create new app (using template calling freshly updated Notificed app)
- create user
- edit user with avatar
- make user admin
- go to admin panel, view user/click edit on user record

<img width="661" alt="Screen Shot 2020-08-20 at 17 44 01" src="https://user-images.githubusercontent.com/6930/90800591-c6a47200-e30c-11ea-9f0d-84e04388f982.png">

I've seen some hints on the Jumpstart forum itself suggesting commenting out the Avatar lines, but I imagine this isn't intended default behaviour? PS I note on your demo heroku app the 'image attachment' on Products is just a plain URL, so I'm guessing this iteration hasn't made it that far?

To try and correct I have...
- installed the  [administrate-field-active_storage](https://github.com/Dreamersoul/administrate-field-active_storage)  gem, which changes the error, replacing 
```
    # avatar_attachment: Field::HasOne,
    # avatar_blob: Field::HasOne,
```
with
```
    avatar_attachment: Field::ActiveStorage,
```
and the error changes...but no dice. FWIW I also tried swapping your version of the Administrate gem for the authoritative one, but same problem.

<img width="627" alt="Screen Shot 2020-08-20 at 18 05 34" src="https://user-images.githubusercontent.com/6930/90802869-c659a600-e30f-11ea-8e68-bdb1537fba5f.png">

Again, happy to help test if required! (And nuke my project cos I haven't got anything done yet!!)

**Comment by excid3** [comment]
Hey David! Yeah, this definitely needs fixing. We didn't always have avatar uploads with ActiveStorage, so that field does need changing. I'm not sure if we'll have to do a gsub on the generated Administrate dashboard or what. I really wish they supported that built-in.

This may be a good opportunity to add the ActiveStorage field directly into my fork of Administrate that we use.

**Comment by excid3** [comment]
Since this is an issue with Administrate, I'm probably going to close this and try and work on it in my Administrate fork instead.

**Comment by loeckelt** [comment]
+1 on this one. I am facing the same issue. Thanks for the fix in the Administrate fork in advance! 👍
