### ISSUE TITLE
Rubocop clashes with definition of class

### ISSUE THREAD

**Issue by martinstreicher** [excid3/jumpstart#109]
(In Jumpstart Pro at least...)

The class in _models/user/connected_account.rb_ is defined as: 

```
class User::ConnectedAccount < ApplicationRecord 
```

The Rubocop `Style/ClassAndModuleChildren` wants to change this per best practice to...

```
  module User 
    class ConnectedAccount < ApplicationRecord
```

... but since there is also a class `::User`, this makes Ruby very upset. 

Likely, `User` should not be used as the prefix and something like `UserRelated` or `UserConnected` would be a better namespace to avoid clashes. This clash also occurs in the test _app/models/user/connected_account.rb_ once Rubocop runs across the latter file.

**Comment by excid3** [comment]
This is Jumpstart's free version which is completely different. I'm going to close this since it's not related.

And it's fine to use classes nested in classes in Ruby. We use Standardrb, not Rubocop directly and Standard does not complain about that.
