### ISSUE TITLE
Error on new install: Sprockets::Rails::Helper::AssetNotPrecompiled

### ISSUE THREAD

**Issue by katzgrau** [excid3/jumpstart#110]
Same issue as #100 — but from that issue it looks like it was possibly fixed, but still an issue for me.

I'm evaluating Jumpstart free in anticipation of the Pro version. I know the codebase is different but I just wanted to get a feel for it.

I'm on ruby v2.6.6 and rails 6.0.3.3

![image](https://user-images.githubusercontent.com/134221/93281209-a051e500-f799-11ea-819a-11824e4b0f6e.png)

**Comment by katzgrau** [comment]
Just a note, disabling the check in `development.rb` gets me around it for now:

    config.assets.check_precompiled_asset = false

**Comment by excid3** [comment]
It'd be helpful to know what you were trying to access here in Administrate. You didn't include any of that in your screenshot.

Since this comes from Administrate, it's related to their bugs.

**Comment by katzgrau** [comment]
@excid3 I was just trying to visit the admin section from the dropdown on the top right (`/admin`)

**Comment by excid3** [comment]
Replicated it and added a fix. 👍 

You have to manually add these lines to `app/assets/config/manifest.js` according to the readme. I've updated the template to do that automatically.

```ruby
//= link administrate/application.css
//= link administrate/application.js
```

Administrate has not updated to work with Sprockets 4. Can't wait to drop that dependency.
