### ISSUE TITLE
Is there a version of this template without administrate?

### ISSUE THREAD

**Issue by spacerobotTR** [excid3/jumpstart#114]
I love this template but I would love to have the admin namespace be vanilla so I can build my own and not have administrate there at all. Is there a version of this without it? Or is there a procedure on removing it after install?

**Comment by excid3** [comment]
We no longer run the Administrate installer by default since their gem is broken, it just adds the gem. You can just remove the gem and you're set. 👍

**Comment by spacerobotTR** [comment]
Thanks!
