### ISSUE TITLE
Add Bootstrap5

### ISSUE THREAD

**Issue by stevenbuccini** [excid3/jumpstart#116]
Since I'm starting a new project anyways, I figured it would be easier to go ahead and use Bootstrap 5 (even though it's in alpha) rather than building on top of Bootstrap 4 and having to worry about upgrading later.

I was wondering if there would be any interest in opening up a branch of this repo where we could implement Bootstrap 5 changes. From there, we can audit the codebase any time an additional development version of Bootstrap is released for any migration steps that might be necessary

Here are some issues that I see at the moment:
- Bump the `bootstrap` Gem included in Gemfile
- Audit code in `app/views/` and `lib/templates/erb/scaffold/` to pull in any migration fixes outlined in the [Bootstrap docs](https://v5.getbootstrap.com/docs/5.0/migration/).
- Update `devise-bootstrap` to pull in Bootstrap 5 fixes. I have migrated all issues I could find up to 5.0.0.alpha3 [here](https://github.com/afomera/devise-bootstrapped/pull/8).

I am happy to make these changes but I wanted to see if there was any interest and if so, get feedback on the approach, before I spend the time doing so.

Thanks!

**Comment by excid3** [comment]
If you want to start a PR for this, that'd be great. I've been thinking about doing the same but just don't have the time. 👍

I probably won't merge it until Bootstrap gets to a Release Candidate just so we're not breaking too many builds along the way.

**Comment by stevenbuccini** [comment]
Sounds great! I'll put up a PR soon. I agree with not merging into master yet. I was thinking about having a release branch that users could clone from, if they wished, until Bootstrap 5 is released. I also think it will be easier to migrate if we do it incrementally, as Bootstrap releases new versions, then doing it in one fell swoop at the end. What do you think?

**Comment by excid3** [comment]
Yep! That sounds good to me. It should just be as simple as changing the branch in the URL version of the instructions.

Also I think it might be nice to copy the devise-bootstrapped views into Jumpstart's repo so we can easily tweak those going forward.
