### ISSUE TITLE
NameError in Admin::Users#new

### ISSUE THREAD

**Issue by githubble01** [excid3/jumpstart#121]
Hi!

I Just started exploring jumpstart, and got an admin account set up. Looks great!

When I try to add a new user I get this error.

![image](https://user-images.githubusercontent.com/1576706/106901564-38744a80-66f8-11eb-96db-3fa9820b87b0.png)

Do the warnings during the installation have anything to do with this?

BR
Georg

```
WARNING: Unable to generate a dashboard for ActionText::RichText.
       - Administrate does not yet support namespaced models.
       - It is not connected to a database table.
         Make sure your database migrations are up to date.
WARNING: Unable to generate a dashboard for ActionMailbox::InboundEmail.
       - Administrate does not yet support namespaced models.
       - It is not connected to a database table.
         Make sure your database migrations are up to date.
WARNING: Unable to generate a dashboard for ActiveStorage::Blob.
       - Administrate does not yet support namespaced models.
WARNING: Unable to generate a dashboard for ActiveStorage::Attachment.
       - Administrate does not yet support namespaced models.
       - 
```

**Comment by githubble01** [comment]
UPDATE: Found a workaround in #111 that did the trick for now..

**Comment by excid3** [comment]
Glad you found that thread. 👍 

I'm actually working on github.com/excid3/madmin as a replacement and I think it should be _about_ ready to start using in Jumpstart. Might try that today actually.

**Comment by excid3** [comment]
I just opened #122 to replace it with Madmin. It seems to be working great, but we're just finishing up some things in Madmin before we release version 1.0. Might do that tonight.

**Comment by githubble01** [comment]
Wow! Looking forward to trying that out. BTW I have to say that I'm very impressed with jumpstart. Educational and effective at the same time.

**Comment by excid3** [comment]
Thanks @githubble01, that means a lot! 🙏
