### ISSUE TITLE
Jumpstart and Reflex Issues

### ISSUE THREAD

**Issue by eclectic-coding** [excid3/jumpstart#127]
Chris,
I tried this template, which I love, recently on a project and a default install of Stimulus Reflex does not work out of the box.

### Steps to Reproduce
- Setup new project with Jumpstart
- Install and setup Stimulus Reflex per setup instruction from [StimulusReflex](https://docs.stimulusreflex.com/hello-world/setup)
```
bundle add stimulus_reflex
bundle exec rails stimulus_reflex:install
```
- Make sure `Redis` is running.
- Add the following test reflex to `index.html.erb`:
```ruby
<a href="#"
  data-reflex="click->Counter#increment"
  data-step="1" 
  data-count="<%= @count.to_i %>"
>Increment <%= @count.to_i %></a>
```
- Added `app/reflexes/counter.rb` and restart foreman:
```ruby
class CounterReflex < ApplicationReflex
    def increment
      @count = element.dataset[:count].to_i + element.dataset[:step].to_i
    end
  end
```
- Start app with foreman and action cable does not start with the following error message:
```shell
06:34:07 web.1     | Started GET "/cable" for 127.0.0.1 at 2021-04-26 06:34:07 -0400
06:34:07 web.1     | Started GET "/cable/" [WebSocket] for 127.0.0.1 at 2021-04-26 06:34:07 -0400
06:34:07 web.1     | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
06:34:07 web.1     | An unauthorized connection attempt was rejected
06:34:07 web.1     | Finished "/cable/" [WebSocket] for 127.0.0.1 at 2021-04-26 06:34:07 -0400
```
I have confirmed that the same steps work successfully with a base `rails new` without Jumpstart.

**Comment by excid3** [comment]
Make sure you're logged in as ActionCable is configured to require a signed in user.

**Comment by eclectic-coding** [comment]
That did it thanks...
