### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by jasoncharnes** [excid3/jumpstart#13]

**Comment by brenoperucchi** [comment]
Oliver, running a new implementation of rails new it should have the optional: true in the polymorphic relation?

```ruby
  class Notification < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :actor, class_name: "User"
    belongs_to :notifiable, polymorphic: true, optional: true
```  

<img width="1017" alt="Screen Shot 2020-04-02 at 23 59 57" src="https://user-images.githubusercontent.com/367967/78319970-bf87ed80-753e-11ea-9204-9951bd1f51b2.png">

**Comment by excid3** [comment]
That would let you create a notification that doesn't point to any record. Maybe that would be useful, but these notifications were designed to notify you about something happening to a record which is why it's required.

**Comment by excid3** [comment]
Now uses https://github.com/excid3/noticed
