### ISSUE TITLE
No /admin route even after setting user admin=true

### ISSUE THREAD

**Issue by jpwynn** [excid3/jumpstart#131]
Folllowing the video, I tried:
```
rails c
User.last.update admin: true
User.last     # to confirm I see:
                   # ...... admin: true ..........
```

But the user's drop down still shows only Settings and Logout (no Admin).

Navigating to /admin  gives: No route matches [GET] "/admin"

Logged out, logged in, same thing.

Quit and restarted `foreman start`, same thing.

Was there another step required to enable the admin area?

There is no dashboards folder, as shown in your Jumpstart Ruby on Rails Template Walkthrough video.

**Comment by jpwynn** [comment]
Ah, looking at the madmin gem, I tried `rails g madmin:install` and that worked now I have the dashboard.

Is that documented on the readme or shown in the video? (I'd assumed incorrectly that wold have been executed by the template)

**Comment by excid3** [comment]
It's printed out in the instructions after your app is created. https://github.com/excid3/jumpstart/blob/master/template.rb#L241-L252
