### ISSUE TITLE
Pro vs non-pro: a comparison table anywhere (either here, or on the Pro site)?

### ISSUE THREAD

**Issue by jpwynn** [excid3/jumpstart#133]
It's very cool you offer this "jumpstart" flavor for free (despite my grumbling elsewhere about dependency issues because no dockerfile). It seems like a  very helpful alternative to just rolling-your-own from scratch with some nice, sensible defaults for gems and stubbed out configuration.

And I think it's cool you offer a low-cost pro option, the price of which probably pays for itself in saved developer time if you need any _one_ feature, for example multi-tenancy or TFA.

But I think it would be helpful - to both Pro and non-Pro users - to publish somewhere a list of Pro vs non-pro features, beyond just "includes payments with Stripe & Braintree, team accounts, TailwindCSS, _and much more_"

For people like me contemplating Pro, it would be nice to understand explicitly what I am - and am not - looking at in this repo vs what to expect with Pro.

For people not currently contemplating Pro, nothing wrong with a list of ideas for extending this repo on their own.

For example...  some things mentioned in Pro docs that might or might not be in this repo:
* the whole /jumpstart configuration wizard is pro-only, right?
* how about the recently added TFA, is that pro-only? 
* any kind of multi-tenancy, support, pro-only?
* User masquerading? (seems to be _installed_ in this repo but the actual feature not _implemented_ correct?)

And, if supported in pro, some things not (yet) explicitly mentioned in the Pro docs:
* Test coverage, does pro have more than 0?
* Any kind of Enhanced admin (such as "search users to find johndoe@example.com")? 
* Any kind of theme-ing? 
* Sortable columns that toggle ASC/DESC?
* Any support for Parent/Child multi-tenancy? (example School accounts "have_many" Student accounts, both can have a Team of Users who can access their respective account)

**Comment by bbugh** [comment]
I ended up here looking for "jumpstart vs jumpstart pro comparison", and this is the only meaningful search result. I was checking the documentation, expecting to see something like a bad for "PRO ONLY" or something, and nothing there either. It's a bit confusing, as I see this repo is still rather active. 

Is there a comparison somewhere that the search engines just can't find? What is the difference between this repo and Pro?

**Comment by bbugh** [comment]
@excid3 great, thanks for the reply about the differences between this repo and the Pro tool, that's helpful for my clients to decide on a course of action. And also thanks all of the awesome Rails stuff you do!

**Comment by excid3** [comment]
Thanks @bbugh! Hit me up anytime if you have more questions! Always happy to help. 👍
