### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by friendlyantz** [excid3/jumpstart#134]
Hey guys, first contribution / issue here.
While being a newbie, I had some trouble setting up the app / `foreman` initially due to lack of knowledge Re redis / sidekiq

I would love to add the below notes to the bottom of the ReadMe to help noobs like me carry on with your template which I absolutely love as well as GoRails content, that helps me immensely!
___________
#### Enabling Admin Panel
App uses `madmin` [gem](https://github.com/excid3/madmin), so you need to run the madmin generator:

```
rails g madmin:install
```

This will install Madmin and generate resources for each of the models it finds.
##### On OSX
```
brew update
brew install redis
brew services start redis
```
##### Ubuntu
```
sudo apt-get install redis-server
```

**Comment by fiveNinePlusR** [comment]
for a simple readme change like that you can propose the edit directly inside github and it will create the pull request for you.

**Comment by friendlyantz** [comment]
Great, thanks for quick response. PR drafted #135

**Comment by friendlyantz** [comment]
Also, I would like to start contributing to open source, in case you guys have some tasks to get me started! Many thanks
