### ISSUE TITLE
Test failing due order of arguments

### ISSUE THREAD

**Issue by fig** [excid3/jumpstart#136]
On my system (manjaro-linux) the TemplateTest is failing due to the order of the arguments passed to `rails new`

Failing: `system("DISABLE_SPRING=1 SKIP_GIT=1 rails new -m template.rb test_app")`
Passing: `system("DISABLE_SPRING=1 SKIP_GIT=1 rails new test_app -m template.rb")`

Is this a platform dependant issue, or a change to the rails executable?

```
$ rails -v
Rails 6.1.3.2
```

```
$ rails new -h
Usage:
  rails new APP_PATH [options]

  ...
```

**Comment by excid3** [comment]
Seems platform specific since the first one works fine on my Mac. It would be fine to change it to use the second one as that should work everywhere too.

**Comment by fig** [comment]
Thank you, Chris. Getting some very strange behaviour here with apps taking the name of the last option if the [APP_NAME] is placed after the options! :scream:
