### ISSUE TITLE
New Install: PG::UndefinedTable: ERROR:  relation "active_storage_attachments" does not exist

### ISSUE THREAD

**Issue by bmx269** [excid3/jumpstart#142]
I ran a clean install of the Jumpstart starter kit, and on a new user signup, I get the error: 

```
ActiveRecord::StatementInvalid in Home#index
Showing /app/views/shared/_navbar.html.erb where line #32 raised:

PG::UndefinedTable: ERROR:  relation "active_storage_attachments" does not exist
LINE 8:  WHERE a.attrelid = '"active_storage_attachments"'::regclass
                            ^     
   base_url_params = "?s=#{size}&d=#{default_image}"

    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size, { gravity: 'Center' }])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
```

I can not find any information on this.

**Comment by excid3** [comment]
Sounds like `rails active_storage:install` didn't succeed / create the models.

**Comment by bmx269** [comment]
@excid3 that fixed the error. Strange that it did not run.

**Comment by excid3** [comment]
Yeah, definitely weird. I haven't noticed that myself, but if you do try it again and it happens, send me those logs and I'll get it fixed. 👍

**Comment by bmx269** [comment]
@excid3 ran the install again, and got the same error. Which logs would you like?

**Comment by excid3** [comment]
Everything you got 😄

**Comment by bmx269** [comment]
[development.log](https://github.com/excid3/jumpstart/files/7022655/development.log)
[jumpstartrails-install-log.txt](https://github.com/excid3/jumpstart/files/7022656/jumpstartrails-install-log.txt)

@excid3 Here is the terminal output on install, and the development log in the app. I can give an application trace if you need.

**Comment by excid3** [comment]
Thanks! The install log is what I need. 

I don't see any errors, but I also don't see it running the `active_storage:install` command either. Very interesting. Will dig in deeper this weekend or something.

**Comment by fiveNinePlusR** [comment]
FWIW I just ran the same command and it finished the install correctly... the output ends with Jumpstart app successfully created! and some instructions to create the db and start it up. For some reason either the script stopped running at the wheneverize command right before it sets up active storage or the output of the command got truncated. Would be helpful if @bmx269 would attach what ruby/rails combo they are running the command with.  

maybe it would be worth having some kind of command queue to add all the commands to and then update the user on completion of a given task how far into the install it is. 

something like : 
```ruby
add_command add_gems
add_command run_webpacker
run_commands
```
outputs:

```
running add_gems (1/2)
running run_webpacker(2/2)
```

might not be worth it but it wouldn't be too hard to implement.

**Comment by bmx269** [comment]
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
Rails 6.1.4.1

**Comment by fiveNinePlusR** [comment]
I just tried it again with 3.0.1p64 and rails 6.1.4.1 and it worked. 

```
 create mode 100644 test/system/.keep
 create mode 100644 test/test_helper.rb
 create mode 100644 tmp/.keep
 create mode 100644 tmp/pids/.keep
 create mode 100644 vendor/.keep
 create mode 100644 yarn.lock

Jumpstart app successfully created!

To get started with your new app:
  cd smallrobot2

  # Update config/database.yml with your database credentials

  rails db:create db:migrate
  rails g madmin:install # Generate admin dashboards
  gem install foreman
  foreman start # Run Rails, sidekiq, and webpack-dev-server
~/p/o/r/h/bug142 ❯❯❯ rails --version
dRails 6.1.4.1
~/p/o/r/h/bug142 ❯❯❯ ruby --version                                                                                                                                                                                              ✘ 1
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin17]
```

**Comment by excid3** [comment]
@fiveNinePlusR did it create the ActiveStorage migrations for you though? It seems to run the template successfully, but I didn't see it copying over the migrations.

**Comment by fiveNinePlusR** [comment]
Yeah, I just did them again and here's the relevant output:

```
[add] writing `./config/schedule.rb'
[done] wheneverized!
       rails  sitemap:install
created: config/sitemap.rb
       rails  active_storage:install
Copied migration 20210821205950_create_active_storage_tables.active_storage.rb from active_storage
         run  git init from "."
```

and it i confirmed that the migration exists in the migrations folder. 

tried it on ruby 2.6.6 and again on ruby 3 and it worked(created the active storage migration) both times.
