### ISSUE TITLE
Noticed generator tries to access database which hasn't been created yet

### ISSUE THREAD

**Issue by brycetelfer** [excid3/jumpstart#151]
During template install on Rails 7:

```
       rails  generate noticed:model
    generate  model
       rails  generate model Notification recipient:references{polymorphic} type params:jsonb read_at:datetime:index
/home/brycetelfer/.rvm/gems/ruby-3.0.2/gems/activerecord-7.0.0.alpha2/lib/active_record/connection_adapters/postgresql_adapter.rb:81:in `rescue in new_client': We could not find your database: myapp_development. Which can be found in the database configuration file located at config/database.yml. (ActiveRecord::NoDatabaseError)
```

**Comment by gathuku** [comment]
I have seen you don't actually run the migration on the template. Can we remove this line https://github.com/excid3/jumpstart/blob/5f292d166d6f4bb8b41f5a32b9eaf7791795d127/template.rb#L199 and have `say rails g noticed:install` at the bottom.

**Comment by excid3** [comment]
The other thing I'm thinking is what if all of Jumpstart becomes an app:template you apply to an existing app? I don't think we really need this to be on a brand new app anymore?
