### ISSUE TITLE
Uninitialized constant HomeController on Rails 7.0.1 fresh install

### ISSUE THREAD

**Issue by thomasgallagher** [excid3/jumpstart#169]
Hi Chris,

Not sure if you support 7.0.1 yet but I get an exception on fresh install

ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-darwin21]
Rails 7.0.1
[output.log](https://github.com/excid3/jumpstart/files/7852755/output.log)

Did I miss something?

Many thanks, Tom

**Comment by excid3** [comment]
Did it not copy the home_controller over?

**Comment by thomasgallagher** [comment]
Doesn't look like it, although the root route does exist.

![Screenshot 2022-01-14 at 11 41 31](https://user-images.githubusercontent.com/11466/149510120-e5a5e039-06af-4ba1-a679-68c8d2cff03c.png)

**Comment by excid3** [comment]
On this line, we copy the whole `app` directory over, so it seems like that didn't run for you or something. https://github.com/excid3/jumpstart/blob/master/template.rb#L134

Have you tried generating a new app more than once to see if it's repeatable?

**Comment by thomasgallagher** [comment]
Hmm, yeah I see that line so that is strange.

The problem is replicable each time I generate a new app. Tried ruby 2.7.2 and Rails 6.1 both with the remote script and with the cloned repository - same result.

The test also fails:
[test.log](https://github.com/excid3/jumpstart/files/7871064/test.log)

I am on MacOS 12.1 (Intel) if that makes any difference (filesystem perms perhaps?)?

T

**Comment by excid3** [comment]
I've been testing with Ruby 3 and Rails 7, but I wouldn't expect those to affect it.

What's interesting is it appears to have stopped after the `add_javascript` line and stopped before adding announcements. I'll have to see if I can replicate this.

**Comment by thomasgallagher** [comment]
👍

Let me know if I can help in any way...

**Comment by excid3** [comment]
Just ran this a bunch of times tonight with no issues. Going to close this, but feel free to reopen if you can figure out a way to reproduce the issue. 👍

**Comment by thomasgallagher** [comment]
Hey Chris,

Figured it out, I didn't have yarn installed.
I would have added it to the README in a PR, but it's already there.
Sorry for wasting your time.

T

**Comment by excid3** [comment]
Ah that would do it!
