### ISSUE TITLE
Duplicate `Gemfile` entry for `cssbundling-rails` when creating a new app

### ISSUE THREAD

**Issue by andyw8** [excid3/jumpstart#170]
When creating a new app with Rails 7.0.1, the following warning is emitted:
```
Your Gemfile lists the gem cssbundling-rails (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
```

I checked the `Gemfile` and `cssbundling-rails` is indeed listed twice.

**Comment by excid3** [comment]
What was your create command?

**Comment by andyw8** [comment]
`rails new myapp -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb --skip-javascript` (from the `README`).

Could it be because Rails now includes `css-bundling` by default, but it's also added by https://github.com/excid3/jumpstart/pull/153 ?

**Comment by excid3** [comment]
Hmm, Rails shouldn't be including `css-bundling` by default. It should just use the asset pipeline.

**Comment by andyw8** [comment]
Sorry, my mistake, I had `--css bootstrap` within my `~/.railsrc` from some previous work.

**Comment by excid3** [comment]
You won't be the only one that adds `--css`

**Comment by andyw8** [comment]
Yeah, that seems sensible. I'll take a look at adding a check for that.

**Comment by excid3** [comment]
Sounds good, let me know if you have any questions. 👍
