### ISSUE TITLE
New app fails to boot, `Could not resolve "./application"`

### ISSUE THREAD

**Issue by andyw8** [excid3/jumpstart#171]
On a new Rails 7.0.1 app, running `bin/dev` fails with:
```
10:46:36 css.1    | $ sass ./app/assets/stylesheets/application.bootstrap.scss ./app/assets/builds/application.css --no-source-map --load-path=node_modules --watch
10:46:36 js.1     | $ node esbuild.config.js --watch
10:46:36 js.1     | ✘ [ERROR] Could not resolve "./application"
10:46:36 js.1     |
10:46:36 js.1     |     controllers/index.js:1:28:
10:46:36 js.1     |       1 │ import { application } from "./application";
10:46:36 js.1     |         ╵                             ~~~~~~~~~~~~~~~
10:46:36 js.1     |
10:46:36 js.1     | error Command failed with exit code 1.
```

Command use to create:
`rails new hello_jumpstart -d postgresql -m https://raw.githubusercontent.com/excid3/jumpstart/master/template.rb --skip-javascript`

Commenting out that line allows the app to boot.

**Comment by excid3** [comment]
Is there no `app/javascript/controllers/application.js` file?

**Comment by andyw8** [comment]
Update: It's due the `--skip-javascript` option. If I run without that, `app/javascript/controllers/application.js` is created and the app can boot.

**Comment by excid3** [comment]
Ah yes. And you know, we should probably be copying the `application.js` from this repo anyways. 

Probably just need to add it around here: https://github.com/excid3/jumpstart/blob/master/template.rb#L123

**Comment by excid3** [comment]
Want to take a stab at that?

**Comment by excid3** [comment]
This should be fixed in 5f4a5f8 👍

**Comment by andyw8** [comment]
Beat me to it 😁

**Comment by excid3** [comment]
Sometimes you just need an easy PR to finish the day off. 😎
