### ISSUE TITLE
NameError in Madmin::Users#new

### ISSUE THREAD

**Issue by sabettaconsulting** [excid3/jumpstart#180]
In a fresh install of jumpstart when I attempt to go to the Madmin Users section and add a user I get the following error:

uninitialized constant NotificationResource

![Screen Shot 2022-02-24 at 5 01 07 PM](https://user-images.githubusercontent.com/70450072/155614903-06d97513-e768-492e-8f14-3f84a4d7fcc0.png)

The App is running on Ruby 3.0.2 and Rails 7.0.2.2

This is my first time submitting an issue so if any more info is needed please let me know!

**Comment by nwclouddev** [comment]
Not sure if this helps, but I encountered this as well. Issue cleared once I generated a notification record. Most likely be an issue of handling nil records returned.

Best,

Adam 

On Feb 24, 2022, at 14:03, Andrew ***@***.***> wrote:

﻿


In a fresh install of jumpstart when I attempt to go to the Madmin Users section and add a user I get the following error:

uninitialized constant NotificationResource

 <https://user-images.githubusercontent.com/70450072/155614903-06d97513-e768-492e-8f14-3f84a4d7fcc0.png> 

The App is running on Ruby 3.0.2 and Rails 7.0.2.2

This is my first time submitting an issue so if any more info is needed please let me know!

**Comment by excid3** [comment]
Do you have a Notification model that doesn't have a madmin resource?

**Comment by pconley** [comment]
Same error.  I am coming back to rails and jumpstart after years away.  Fresh install... there seems to be no model created for notification... but it is referenced in (for example) users.
