### ISSUE TITLE
Fails at add_esbuild_script set-script deprecated in npm v9

### ISSUE THREAD

**Issue by fordnox** [excid3/jumpstart#190]
[This check](https://github.com/excid3/jumpstart/blob/7afb68b401040dea5c324528c915dc0cc1be7599/template.rb#L218) expect npm version >7 
[v8](https://docs.npmjs.com/cli/v8/commands) includes this command. which was good until [v9](https://docs.npmjs.com/cli/v9/commands) where it was deprecated. 

Add another solution for when npm version > 9

My versions:

❯ ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]

❯ npx -v
9.2.0

❯ npm -v
9.2.0

**Comment by Ray-Hughes** [comment]
Upgrading to node v16.14.0 and npm 8.3.1 should be a workaround for this

**Comment by excid3** [comment]
We can update this to match what Rails does. https://github.com/rails/jsbundling-rails/blob/main/lib/install/esbuild/install.rb
