### ISSUE TITLE
Rails 6.1 errors

### ISSUE THREAD

**Issue by eclectic-coding** [excid3/jumpstart#198]
The other day, I tried to spin up a Rails 6.1 Jumpstart app, just for a reference.

The installation never finished, and was a mix between webpacker and a failed esbuild configuration.

I am not sure if you still want to support Rails 6.1, and if so, the configuration you are looking to support. With a little direction, I will be glad to look into a PR to fix the issues.

**Comment by eclectic-coding** [comment]
Do we want to remove the < 7 code and end with a warning to user that Jumpstart requires Rails 7+ for now, or leave as is?

**Comment by excid3** [comment]
That would be great!
