### ISSUE TITLE
Omit `config.action_mailer.default_url_options` in next release of Rails

### ISSUE THREAD

**Issue by stevepolitodesign** [excid3/jumpstart#211]
Once https://github.com/rails/rails/pull/51191 is in the next Rails release, we can omit the following line: 

https://github.com/excid3/jumpstart/blob/edfcc4bba8546b99e60eb0feccc78cff382caa6d/template.rb#L79

**Comment by stevepolitodesign** [comment]
@excid3 feel free to close this or move this to a backlog. I just wanted to bring it to your attention 👍

**Comment by excid3** [comment]
Great improvement @stevepolitodesign 👍

**Comment by excid3** [comment]
Going to close this for now since we'll still need this line for older Rails version unless we drop support for them at some point.
