### ISSUE TITLE
Non-english chars in "jumpstart.yml" break the app

### ISSUE THREAD

**Issue by dourosdimitris** [excid3/jumpstart#212]
If for example the name is set to a greek one, the serializer raises error and the app cannot start with:

/rails/lib/jumpstart/lib/jumpstart/yaml_serializer.rb:14:in `match': invalid byte sequence in US-ASCII (ArgumentError)
if (match = /^(\w+):\s*\|-/.match(line))

**Comment by excid3** [comment]
This is not related to the free Jumpstart.
