### ISSUE TITLE
Syntax Errors on devise Login and Log Out controllers.

### ISSUE THREAD

**Issue by darkrubyist** [excid3/jumpstart#29]
![image](https://user-images.githubusercontent.com/11207292/37757812-e3d67dea-2db6-11e8-8a69-a22f03f8922d.png)

**Comment by darkrubyist** [comment]
This is a devise bug as referenced in the following issue.
https://github.com/plataformatec/devise/issues/4630

I was able to fix it by updating Devise version: 4.4.3

**Comment by excid3** [comment]
Just merged your PR for this so it should now be fixed. 👍
