### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by shairyar** [excid3/jumpstart#38]
It will be nice to add a gem that allows user roles

**Comment by excid3** [comment]
👍to that!

**Comment by darkrubyist** [comment]
I recently integrated CanCanCan on my own projects. Maybe we can use that.

**Comment by excid3** [comment]
I'd recommend using Pundit over CanCan, it's a lot simpler in complex situations. May also want to use Rolify for roles.

**Comment by abhinaykumar** [comment]
@excid3 curious to know your thoughts on Roles for User, what different types of roles and permissions are we looking here?

**Comment by excid3** [comment]
We don't really need any roles out of the box since Jumpstart is so simple. That's the main reason I haven't done anything with adding them yet. They aren't really necessary at the moment, it would just be for convenience.
