### ISSUE TITLE
which ruby version, having trouble with scopes 

### ISSUE THREAD

**Issue by toyflish** [excid3/jumpstart#42]
running the generator on ruby 2.5.1 and rails 5.2  fails because of calling limit on the scope proc.
could that be a ruby version issue?

````
    generate  administrate:install
Running via Spring preloader in process 221
[WARNING] Could not load generator "generators/administrate/routes/routes_generator". Error: undefined method `limit' for #<Proc:0x000055ad18d505a0>.
/app/app/models/notification.rb:7:in `<class:Notification>'
````
it's this line in notification.rb https://github.com/excid3/jumpstart/blob/716ca1f51ce065386bd0202f018baa2d9e156927/app/models/notification.rb#L7

**Comment by excid3** [comment]
Whoops! Yeah you're right. That limit should have been inside the lambda, not outside. Just fixed it!
