### ISSUE TITLE
Paranoia?

### ISSUE THREAD

**Issue by excid3** [excid3/jumpstart#5]
Should we have every model use paranoia?

**Comment by thutterer** [comment]
Nowadays, I'd recommend `discard` instead:
https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid

But I'm not sure if I wanted to have this by default on every model either. That would still mean an extra datetime column on every model. And it's really straight-forward to set up yourself.

**Comment by excid3** [comment]
Discard is great. 👍

And yeah, definitely not by default on every model. I think it's simple enough to add the gem that we can probably close this. It doesn't seem like it'll add that much value.
