### ISSUE TITLE
Masquerade missing before_action :masquerade_user!

### ISSUE THREAD

**Issue by feliperaul** [excid3/jumpstart#53]
Masquerade gem documentation states that one must add `before_action :masquerade_user!`. Even tough I don't see it anywhere in the template, masquerading works. 

I'm opening this issue for you guys to review if this is intentionally missing tough.

**Comment by excid3** [comment]
It doesn't seem crucial, but we should definitely have it I think.

It just includes this: https://github.com/oivoodoo/devise_masquerade/blob/1e57d500a100f129f73b1db9494e7bba88a3b5d3/lib/devise_masquerade/controllers/helpers.rb
