### ISSUE TITLE
Make Bootstrap optional?

### ISSUE THREAD

**Issue by nickisnoble** [excid3/jumpstart#54]

**Comment by excid3** [comment]
@nickisnoble I've been wanting to move it to Tailwind CSS instead, but there's almost certainly going to be some sort of css library required for this otherwise you can provide html templates that look any good by default.

**Comment by nickisnoble** [comment]
`+1` Tailwind would be awesome! 

Bootstrap just looks super specific, and I find myself using it less and less. I get that not having styles ready to roll would make the package feel incomplete though

**Comment by foucist** [comment]
I vote for tailwind also 😄

**Comment by jespr** [comment]
@excid3 we could extract some utility patterns using `@apply` the tailwindcss way, to provide some nice defaults for forms, navbar etc?

**Comment by excid3** [comment]
We definitely can replicate the Bootstrap classes in Tailwind to make the transition easier.

I've also been building a small set of Stimulus controllers to replicate the JS functionality of Bootstrap: tabs, modals, dropdowns, etc. Those would be required before we could make the switch I think.

I should get those published on Github soon.

**Comment by richjdsmith** [comment]
StimulusJS + TailwindCSS would be an awesome combo - especially like @jespr said, using some `@apply` for a few defaults. 

Need a hand on this?

**Comment by davidbkay** [comment]
I've had pretty good luck with an AlpineJS/Tailwind combo. Just another option to throw out there.

**Comment by excid3** [comment]
This is probably gonna stick with Bootstrap for the time being. There aren't too many views to port over to Tailwind or your CSS framework of choice. We can reopen or start a PR if someone feels really strong about it.
