### ISSUE TITLE
A few install notes if helpful..

### ISSUE THREAD

**Issue by escapeit** [excid3/jumpstart#55]
Chris, thanks for this. 

1. I cloned this into a rvm gemset (ruby-2.5.1) and (not surprisingly) the install will fail if bundler isn't already installed.

1. Rerunning the install, it got to _"generate  devise:install"_ and bombed. The error was, _"...rvm/gems/ruby-2.5.1/gems/msgpack-1.2.4/lib/msgpack.rb:11:in \`require': incompatible library version - ...rvm/gems/ruby-2.5.1/gems/msgpack-1.2.4/lib/msgpack/msgpack.bundle (LoadError)"_. Not sure of the root of the conflict, but running `rvm gemset empty` and then `gem install bundler`, `gem install rails` allowed the script to finally complete without bombing.

1. Then I attempted to start the server and it failed looking for config/webpacker.yml. The error was, _"RAILS_ENV=development environment is not defined in config/webpacker.yml, falling back to production environment"_. Looking back at the install output, this was also shown right after _"generate  devise:install"_. I didn't have yarn installed at that point; which I presume is why it didn't get installed during the script. I'm on OSX so I ran `brew install yarn` and then needed to run `rails webpacker:install` after that. Golden from that point forward.

Hope this helps. Thanks again!

**Comment by excid3** [comment]
Yeah, it does expect you have Ruby, bundler, rails, and Yarn already installed. Those will be good to add as prereqs to the readme or something.
