### ISSUE TITLE
Undefined method `current_sign_in_at` on fresh install

### ISSUE THREAD

**Issue by nickisnoble** [excid3/jumpstart#58]
Attempting to sign up or log in after a fresh install results in:

<img width="1440" alt="screen shot 2018-09-05 at 12 34 07 pm" src="https://user-images.githubusercontent.com/4031679/45107570-02d26e00-b108-11e8-99da-5664c14179c3.png">

How do I fix this?

**Comment by excid3** [comment]
Devise changed their migration to not add that column. You can uncomment those and redo migrations.

**Comment by excid3** [comment]
And fixed!
