### ISSUE TITLE
Search in admin area causes ActiveRecord::StatementInvalid in Admin::Users#index 

### ISSUE THREAD

**Issue by henricazottes** [excid3/jumpstart#59]
### Versions:
Rails 5.2.1
DB: Sqlite

### Steps to recreate the error:
- Create a Rails app with JumpStart template
- Register a new user / make it admin
- Go to Admin Area and make a search in Users

### Output
ActiveRecord::StatementInvalid in Admin::Users#index 
```
SQLite3::SQLException: no such column: users.password: SELECT  "users".* FROM "users" WHERE (LOWER(CAST("users"."email" AS CHAR(256))) LIKE '%qsdfqsdf%' OR LOWER(CAST("users"."password" AS CHAR(256))) LIKE '%qsdfqsdf%' OR LOWER(CAST("users"."encrypted_password" AS CHAR(256))) LIKE '%qsdfqsdf%' OR LOWER(CAST("users"."reset_password_token" AS CHAR(256))) LIKE '%qsdfqsdf%' OR LOWER(CAST("users"."name" AS CHAR(256))) LIKE '%qsdfqsdf%') LIMIT ? OFFSET ?
```

Search is working fine on Announcements.

**Comment by excid3** [comment]
@henricazottes Try updating the dashboard file to use this for password.

`password: Field::String.with_options(searchable: false)`

**Comment by henricazottes** [comment]
Fixed :)

**Comment by excid3** [comment]
@henricazottes should be fixed more permanently now.

**Comment by aximuseng** [comment]
It's not for me - throws an error when I do a basic search only own name in the admin panel:

`PG::UndefinedColumn: ERROR:  column users.name does not exist`

**Comment by excid3** [comment]
Admin should use `first_name` and `last_name` because `name` is a virtual attribute.

**Comment by aximuseng** [comment]
I agree - what I am saying is the default out of the box install User administrate page is searching on the virtual attribute:

`PG::UndefinedColumn: ERROR: column users.name does not exist\nLINE 1: ... AS CHAR(256))) LIKE '%dan tappin%' OR LOWER(CAST(\"users\".\"n...\n ^\n`

**Comment by excid3** [comment]
I made some updates to Administrate to make it work better. Try using `gem 'administrate', github: 'excid3/administrate', branch: 'jumpstart'` instead. Should work with `name` as their main branch doesn't support virtual attributes anymore and they don't seem to be interested in merging my PR to support them since they merged in something that explicitly chooses not.
