### ISSUE TITLE
Syntax error in user_dashboard.rb in new application from template.

### ISSUE THREAD

**Issue by howtwizer** [excid3/jumpstart#61]
I just try to create new application from template, and have an error in adminstrate page.
This error caused by wrong `ATTRIBUTE_TYPES` hash in user_dashboard.rb.

How it looked in my project after running the template (twice check):

```
  ATTRIBUTE_TYPES = {
    notifications: Field::HasMany,
    services: Field::HasMany,
    id: Field::Number,
    email: Field::String,
		Field::String.with_options(searchable: false),,
    encrypted_password: Field::String,
    reset_password_token: Field::String,
    reset_password_sent_at: Field::DateTime,
    remember_created_at: Field::DateTime,
    first_name: Field::String,
    last_name: Field::String,
    announcements_last_read_at: Field::DateTime,
    admin: Field::Boolean,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze

```

As you see, the problem is with email key, seems that template script not [gsub](https://github.com/excid3/jumpstart/blob/master/template.rb#L156) it correctly for some reason.

Is this my local problem or somebody have this issue too? I see that last [change](https://github.com/excid3/jumpstart/commit/d986efa85232202be278af1769c792440f7c7a15) was mage 22 days ago, but I don't really understand purpose of `\n\t\t` there and trailing comma.

**Comment by excid3** [comment]
Looks like it was missing the key `password` for the field. Should be fixed in 012b2e8
