### ISSUE TITLE
Move from User model to Account model to provide better abstractions in the code.

### ISSUE THREAD

**Issue by stephendolan** [excid3/jumpstart#64]
This free Ruby Tapas episode explains the idea better than I can in text, so give it a watch!

https://www.rubytapas.com/2015/10/01/episode-346-user-model/

This issue is for discussion before I open up a PR, to see if anyone else thinks this could be done in a sensible way for apps using Jumpstart.

**Comment by excid3** [comment]
Just to clarify some other goals around Jumpstart as well:

Long-term we want to have support for both individual accounts and teams. That stuff needs to be ultra clear from naming. Maybe for individual accounts you have a one-person Team or something.

Jumpstart's also intended to be easy for beginners in Rails, and all the tutorials use `current_user` so a change like this would violate a lot of things they take for granted. It might be a good idea, but also might not be worth the confusion.

**Comment by captproton** [comment]
Should this issue be closed?

**Comment by excid3** [comment]
Yeah, I think we'll stick with `current_user` for now.
