### ISSUE TITLE
Thoughts on pulling most recent versions of gems in the template?

### ISSUE THREAD

**Issue by stephendolan** [excid3/jumpstart#65]
I've implemented some basic classes in my `template.rb` that will fetch the most recent version of a gem unless a specific `version` argument is passed. Would this repository benefit from something like this, or are standardized gem versions better for stability?

https://gitlab.com/stephendolan/rails-default-template/blob/master/template.rb

**Comment by captproton** [comment]
@excid3 what do you think?

**Comment by excid3** [comment]
We've needed standardized gem versions, especially lately with Rails 6.0's release, so we'll probably stick to that. I'd love to always use the latest, but dependencies seem to regularly have issues so specific versions are almost a must.
