### ISSUE TITLE
uninitialized constant Service::PROVIDERS (NameError)

### ISSUE THREAD

**Issue by dsugroup** [excid3/jumpstart#66]
Hi Chris,

I just pulled down the latest version and ran accordingly to the documentation but it looks like it has failed for me.

`block in load_missing_constant': uninitialized constant Service::PROVIDERS (NameError)

Have you seen this error before? is it something I don't have installed?

Cheers

**Comment by excid3** [comment]
Yep, getting that error too. Let me fix that real quick.

**Comment by excid3** [comment]
@dsugroup this should be fixed now!

**Comment by dsugroup** [comment]
Thank you @excid3 much appreciated.
