### ISSUE TITLE
`Gemfile`: You cannot specify the same gem -jquery-rails- twice with different version requirements.

### ISSUE THREAD

**Issue by JElbourne** [excid3/jumpstart#68]
You specified: jquery-rails (>= 0) and jquery-rails (~> 4.3.1). Bundler cannot continue.
```
 #  from /Gemfile:65
 #  -------------------------------------------
 #  gem 'gravatar_image_tag', github: 'mdeering/gravatar_image_tag'
 >  gem 'jquery-rails', '~> 4.3.1'
 #  gem 'local_time', '~> 2.0'
 #  -------------------------------------------
```

The default gemfile already has jquery-rails, so a solution could be to simply use that and not include it in the template AddGems method.

**Comment by JElbourne** [comment]
Not a problem with Rails 5.2.x

**Comment by excid3** [comment]
@JElbourne Yeah, 5.2+ is what's currently supported. I'm not sure why you'd want to start a new app with an older version of Rails, but if that's a thing, let me know and we could explore that.

**Comment by JElbourne** [comment]
@excid3 Yes, sorry, I was working on an older project before trying your template and had not been using the newest version of Rails. Completely an oversight on my part and when I realized it, your template worked great.
