### ISSUE TITLE
Can't specify database credentials before generating a new app

### ISSUE THREAD

**Issue by qwrobins** [excid3/jumpstart#75]
Whenever I try and use the template to generate a new app, it fails during the rails db:create step because my dev database doesn't exist on my local system and also requires authentication. It would be really helpful if there were a step that gathered this info.

**Comment by excid3** [comment]
I agree. PR is welcome. 👍

**Comment by qwrobins** [comment]
Thanks @excid3. Might be a bit before I get time but more than happy to.

**Comment by excid3** [comment]
This is fixed in the latest version. We no longer create and migrate as part of the generator.
