### ISSUE TITLE
uninitialized constant NotificationDashboard

### ISSUE THREAD

**Issue by dalton-cole** [excid3/jumpstart#77]
I get the following output when I access the admin dashboard on a fresh install with rails 6. 

`ActionView::Template::Error` (uninitialized constant NotificationDashboard
Did you mean?  Notification):
    18: [1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
    19: %>
    20: 
    21: <% if field.resources.any? %>
    22:   <% order = field.order_from_params(params.fetch(field.name, {})) %>
    23:   <% page_number = params.fetch(field.name, {}).fetch(:page, nil) %>
    24:   <%= render(
  
app/views/admin/users/show.html.erb:48
app/views/admin/users/show.html.erb:39:in `each'
app/views/admin/users/show.html.erb:39
DEPRECATION WARNING: ActionView::Base instances should be constructed with a lookup context, assignments, and a controller. (called from new at /var/lib/gems/2.5.0/gems/web-console-3.7.0/lib/web_console/template.rb:21)`

**Comment by excid3** [comment]
There's currently a bug that Administrate doesn't generate dashboards for most models in Rails 6. I'm not sure if it's a bug in Zeitwerk or in Administrate. I temporarily patched Jumpstart not to choke, but you'll want to manually run Administrate's generator to have it generate the other models for now. 

If anyone's interested in figuring out what's wrong, please take a look. I did fork Administrate to do an `eager_load` in Administrate for loading all the models, but I'm not sure that's the actual problem.

**Comment by dalton-cole** [comment]
I'll take a deeper look, glad to know it is a known issue.

**Comment by excid3** [comment]
For reference, here's the code I added: https://github.com/excid3/administrate/blob/87215d9cf51c31613dda5c276dfe6d6c5bfb010b/lib/generators/administrate/routes/routes_generator.rb#L12-L14
