### ISSUE TITLE
Undefined mixin 'media-breakpoint-down'.

### ISSUE THREAD

**Issue by an-nasir** [excid3/jumpstart#78]
I am getting this error while I try to load my page. In following file
`/home/anasir/myw/scripts/rails-rocket/myapp/app/views/shared/_head.html.erb`
This actually written in following file.
`app/assets/stylesheets/application.scss`

It also taking too much time to load the main page even that has nothing in it. It insanely ~around 2 MINUTES.

**Comment by excid3** [comment]
I wasn't able to reproduce this with Rails 5.2 or 6.0 rc1. Probably will have to give some more detail on your problem.

**Comment by an-nasir** [comment]
I'll give it another try and will post here if it happens again.
