### ISSUE TITLE
Add Webpacker, Sidekiq, and Foreman

### ISSUE THREAD

**Issue by excid3** [excid3/jumpstart#8]
* [x] Webpacker
* [x] Sidekiq
* [x] Foreman
* [x] Copy over Procfile
* [x] Set Sidekiq as the queue adapter in `config/application.rb`

```bash
#Procfile
web: rails server
webpacker: bin/webpack-dev-server
sidekiq: sidekiq
```

queu

**Comment by shairyar** [comment]
Webpack does not seem to be taking any changes made in scss file? am i missing something? I did not make any changes to it just testing things out.
