### ISSUE TITLE
Administrate fails on deploy to Hatchbox

### ISSUE THREAD

**Issue by dalton-cole** [excid3/jumpstart#80]
Trying to deploy to hatchbox with a vanilla version of the jumpstart template but it keeps timing out. When I check the puma logs, I see this

`/app/controllers/concerns/administrate/punditize.rb to define constant Administrate::Punditize, but didn't`

It runs fine locally and I don't see anything in the gitignore file that would remove a concern file.

**Comment by excid3** [comment]
Sounds like maybe a Zeitwerk bug. https://github.com/thoughtbot/administrate/issues/1048#issuecomment-488606728

**Comment by dalton-cole** [comment]
You are correct. 
Adding the pundit to the gem file works as a temp fix while pundit awaits patching for rails 6.

**Comment by excid3** [comment]
We've been working on a new admin during Railsconf, so hopefully we can release that soon and replace it with our own. :D

**Comment by bingxie** [comment]
I got the same issue after upgrading to rails 6 and deploying to heroku.

**Comment by excid3** [comment]
Hey guys, sorry this took me a while to fix.

I've started maintaining a fixed version of administrate for now with fixes. Switch your Gemfile to the Github branch and that should fix it.

```ruby
gem 'administrate', github: "excid3/administrate", branch: 'jumpstart'
```
