### ISSUE TITLE
Fail to push to heroku

### ISSUE THREAD

**Issue by lf2foce** [excid3/jumpstart#81]
Hello Christ, I dont know why it worked awesome on local machine but fail to push to heroku, any idea?
Ps: I have alread installed addon redistogo on heroku but still dont work.

**Comment by excid3** [comment]
You'll have to post some information about what went wrong.

**Comment by carterfiber** [comment]
Mine stopped pushing to heroku, too... Keeps saying failed to precompile
assets. I've been scouring the web for some type of solution but nothing
has worked yet

All the best,

Gerald Carter

**Comment by lf2foce** [comment]
`remote: ###### WARNING:
remote: 
remote:        Detecting rails configuration failed
remote: 
remote: ###### WARNING:
remote: 
remote:        We detected that some binary dependencies required to
remote:        use all the preview features of Active Storage are not
remote:        present on this system.
remote:        
remote:        For more information please see:
remote:          https://devcenter.heroku.com/articles/active-storage-on-heroku
remote:        
remote: 
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types     -> web, worker
remote:        Default types for buildpack -> console, rake
remote: 
remote: -----> Compressing...
remote:        Done: 103.5M
remote: -----> Launching...
remote:        Released v8
remote:        https://bdsmetric4.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/bdsmetric4.git
   b780988..eb46f18  master -> master`
here is log, I tried to search around this error on stackover.

**Comment by lf2foce** [comment]
Hey all, I just find a solution to this, 
Add:
gem 'pundit', '~> 1.1.0'

**Comment by captproton** [comment]
Is this issue resolved?
