### ISSUE TITLE
Remove avatar option

### ISSUE THREAD

**Issue by aximuseng** [excid3/jumpstart#82]
The users should be able to clear / remove their avatar.

**Comment by excid3** [comment]
This would be a good first issue if anyone wants to submit a PR for this.

**Comment by scswan85** [comment]
Do you want it to be something like the admin has the ability to remove gravatars for the entire app or individual users can opt to grey out the gravatar sort of thing?

**Comment by excid3** [comment]
Just clearing their ActiveStorage avatar, not Gravatar actually.
