### ISSUE TITLE
Jumpstart Configuration Page

### ISSUE THREAD

**Issue by jasper502** [excid3/jumpstart#84]
What is the best practice to hide the configuration page?

Currently I have my production server behind basic http auth otherwise the configuration page is wide open to anyone to edit etc.

I would suggest that perhaps the initial set-up workflow should be:

1. create a first user (admin by default)
2. on your first login you get the configuration page and be forced to complete it
3. afterwards only the admins can access the configuration page

**Comment by excid3** [comment]
This is the free Jumpstart repository and it doesn't have a configuration page.

Jumpstart Pro's configuration is only enabled in development.

**Comment by jasper502** [comment]
Just opened a thread....

**Comment by excid3** [comment]
Replied on there with a fix. Should be good now. 👍
