### ISSUE TITLE
Suggested gems

### ISSUE THREAD

**Issue by ohaddahan** [excid3/jumpstart#87]
I recommend adding by default:
https://github.com/ohler55/oj
https://github.com/typhoeus/typhoeus
https://github.com/errbit/errbit
https://github.com/ankane/pghero

And:
https://github.com/fazibear/colorize
I use it for debug prints in color, much easier to see them compared to a regular text print.

**Comment by scswan85** [comment]
This is the basic free version of the Jumpstart template.  Adding things like errbit and the others you're free to install after running the template.  This isn't an actual issue though.

**Comment by asecondwill** [comment]
https://rubygems.org/gems/annotate/

**Comment by asecondwill** [comment]
simple_form of course
