### ISSUE TITLE
NameError in Admin::Users#show - uninitialized constant ServiceDashboard

### ISSUE THREAD

**Issue by smrr723** [excid3/jumpstart#90]
**routes.rb**
```
Rails.application.routes.draw do
  namespace :admin do
      resources :users

      root to: "users#index"
    end
```

**Server Log**
```
16:11:04 web.1     | ActionView::Template::Error (uninitialized constant ServiceDashboard
16:11:04 web.1     | Did you mean?  UserDashboard):
16:11:04 web.1     |     18: [1]: http://www.rubydoc.info/gems/administrate/Administrate/Field/HasMany
16:11:04 web.1     |     19: %>
16:11:04 web.1     |     20: 
16:11:04 web.1     |     21: <% if field.resources.any? %>
16:11:04 web.1     |     22:   <% order = field.order_from_params(params.fetch(field.name, {})) %>
16:11:04 web.1     |     23:   <% page_number = params.fetch(field.name, {}).fetch(:page, nil) %>
16:11:04 web.1     |     24:   <%= render(
16:11:04 web.1     |   
16:11:04 web.1     | app/views/admin/users/show.html.erb:48
16:11:04 web.1     | app/views/admin/users/show.html.erb:39:in `each'
16:11:04 web.1     | app/views/admin/users/show.html.erb:39
16:11:27 web.1     | Started GET "/admin/users/1" for ::1 at 2019-07-14 16:11:27 +0100
```

This error occurs on a new jumpstart installation with `Rails 6.0.0.rc1`, when I visit the path `admin/users/1`.

My solution was to run `rails generate administrate:dashboard Service` which is what is being looked for in the error, though I don't have any Service models.  I don't fully understand why this is being asked for though - it could be clarified in the docs somewhere.

**Comment by scswan85** [comment]
@smrr723 Could have been something wonky with 6.0.0.rc1.  I just loaded up a new 6.0 application using the JumpStart template and the page loads just fine.

**Comment by excid3** [comment]
Administrate and Rails 6 did not play well. I've since forked Administrate and maintain my own copy with fixes so we can use it more reliably now. Probably can close this one.
