### ISSUE TITLE
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by CyHunterX** [excid3/jumpstart#91]
when i use the "foreman start" command i got that error. "Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)" So sidekiq don't work and i cant start the template. Someone know how to fix this? i want test this.

**Comment by king601** [comment]
Hey there,

It sounds like redis isn't running, or isn't installed locally on your dev machine.

If you're running a mac with brew installed, try running 
```
brew install redis
```

```
brew services start redis
```

Otherwise, if you're not running Mac I'd try looking up installation instructions for your operating system

**Comment by CyHunterX** [comment]
thx a lot i even know i need to start the services but thx a lot
